/**
 * The sound design, synthesised from scratch.
 *
 * Every sound in this film is generated by the maths below and written into
 * public/audio as WAV. Nothing is downloaded, so there is no licence attached
 * to any of it and no asset that can go missing at render time.
 *
 * The brief calls the audio "der heimliche Star": a text popping in has a pop,
 * a statistic falling has a low hit, money has a till, danger has a glitch, and
 * underneath all of it a synth bed ticks like a countdown. That is what this
 * file produces — a small kit of short cues plus two looping beds, one for each
 * half of the film.
 *
 * Run with `npm run build:audio`. The output is committed, so a render never
 * depends on this script having run.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const SFX_RATE = 44100;
const BED_RATE = 22050;
const OUT = join(process.cwd(), "public", "audio");

// ---------------------------------------------------------------------------
// A very small synthesis toolkit.
// ---------------------------------------------------------------------------

type Buf = Float32Array;

const buffer = (seconds: number, rate: number): Buf =>
  new Float32Array(Math.round(seconds * rate));

/** Exponential decay envelope: instant attack unless one is given. */
function env(
  i: number,
  length: number,
  { attack = 0.002, decay = 1, curve = 4 } = {},
): number {
  const t = i / length;
  const attackSamples = Math.max(1, attack * length);
  const rise = Math.min(1, i / attackSamples);
  return rise * Math.exp((-curve * t) / decay);
}

/** Exponential ramp — the right shape for anything pitched. */
const pitchRamp = (i: number, n: number, from: number, to: number): number =>
  from * Math.pow(to / from, i / n);

let seed = 0x2f6e2b1;
/** Deterministic noise, so two runs of this script produce identical files. */
function rnd(): number {
  seed ^= seed << 13;
  seed ^= seed >>> 17;
  seed ^= seed << 5;
  return ((seed >>> 0) / 0xffffffff) * 2 - 1;
}

/** One-pole low-pass. `cut` is 0..1, roughly cutoff / nyquist. */
function lowpass(input: Buf, cut: number | ((i: number) => number)): Buf {
  const out = new Float32Array(input.length);
  let last = 0;
  for (let i = 0; i < input.length; i++) {
    const a = typeof cut === "function" ? cut(i) : cut;
    last += Math.max(0.0005, Math.min(1, a)) * (input[i] - last);
    out[i] = last;
  }
  return out;
}

/** One-pole high-pass, as the complement of the low-pass. */
function highpass(input: Buf, cut: number): Buf {
  const low = lowpass(input, cut);
  const out = new Float32Array(input.length);
  for (let i = 0; i < input.length; i++) out[i] = input[i] - low[i];
  return out;
}

function mix(target: Buf, source: Buf, gain = 1, offset = 0): void {
  for (let i = 0; i < source.length; i++) {
    const j = i + offset;
    if (j >= 0 && j < target.length) target[j] += source[i] * gain;
  }
}

/** Scale so the loudest sample sits at `peak`, and remove any DC offset. */
function normalize(buf: Buf, peak = 0.9): Buf {
  let dc = 0;
  for (const s of buf) dc += s;
  dc /= buf.length;

  let max = 0;
  for (let i = 0; i < buf.length; i++) {
    buf[i] -= dc;
    max = Math.max(max, Math.abs(buf[i]));
  }
  if (max > 0) {
    const g = peak / max;
    for (let i = 0; i < buf.length; i++) buf[i] *= g;
  }
  return buf;
}

/** Fade the very edges so nothing starts or ends on a click. */
function deClick(buf: Buf, samples = 64): Buf {
  const n = Math.min(samples, Math.floor(buf.length / 2));
  for (let i = 0; i < n; i++) {
    buf[i] *= i / n;
    buf[buf.length - 1 - i] *= i / n;
  }
  return buf;
}

/**
 * Fold the tail back over the head so the buffer loops without a seam.
 *
 * Remotion restarts a looped clip on a hard boundary, so anything still
 * ringing at the end of the bed would click. Crossfading the tail into the head
 * makes the join inaudible.
 */
function loopSeam(buf: Buf, seconds: number, rate: number): Buf {
  const n = Math.round(seconds * rate);
  const out = buf.slice(0, buf.length - n);
  for (let i = 0; i < n; i++) {
    const w = i / n;
    out[i] = out[i] * w + buf[buf.length - n + i] * (1 - w);
  }
  return out;
}

function writeWav(name: string, data: Buf, rate: number): void {
  const bytes = Buffer.alloc(44 + data.length * 2);
  bytes.write("RIFF", 0);
  bytes.writeUInt32LE(36 + data.length * 2, 4);
  bytes.write("WAVE", 8);
  bytes.write("fmt ", 12);
  bytes.writeUInt32LE(16, 16);
  bytes.writeUInt16LE(1, 20); // PCM
  bytes.writeUInt16LE(1, 22); // mono
  bytes.writeUInt32LE(rate, 24);
  bytes.writeUInt32LE(rate * 2, 28);
  bytes.writeUInt16LE(2, 32);
  bytes.writeUInt16LE(16, 34);
  bytes.write("data", 36);
  bytes.writeUInt32LE(data.length * 2, 40);

  for (let i = 0; i < data.length; i++) {
    const clamped = Math.max(-1, Math.min(1, data[i]));
    bytes.writeInt16LE(Math.round(clamped * 32767), 44 + i * 2);
  }

  const path = join(OUT, name);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.length));

  let rms = 0;
  for (const s of data) rms += s * s;
  console.log(
    `  ${name.padEnd(18)} ${(data.length / rate).toFixed(2)}s  ` +
      `${(bytes.length / 1024).toFixed(0)} KB  rms ${Math.sqrt(rms / data.length).toFixed(3)}`,
  );
}

// ---------------------------------------------------------------------------
// The cues.
// ---------------------------------------------------------------------------

/** Text arriving on screen. A short blip that falls in pitch. */
function pop(): Buf {
  const out = buffer(0.14, SFX_RATE);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    const f = pitchRamp(i, out.length, 1100, 260);
    phase += (2 * Math.PI * f) / SFX_RATE;
    out[i] = Math.sin(phase) * env(i, out.length, { decay: 0.5, curve: 6 });
  }
  const click = buffer(0.006, SFX_RATE);
  for (let i = 0; i < click.length; i++) click[i] = rnd() * (1 - i / click.length);
  mix(out, highpass(click, 0.4), 0.35);
  return normalize(deClick(out), 0.8);
}

/** Movement — a scene arriving, an element sliding in. */
function swoosh(): Buf {
  const n = Math.round(0.38 * SFX_RATE);
  const raw = new Float32Array(n);
  for (let i = 0; i < n; i++) raw[i] = rnd();

  // A band that sweeps up and back down reads as something passing by.
  const swept = lowpass(raw, (i) => 0.02 + 0.5 * Math.sin((Math.PI * i) / n));
  const out = highpass(swept, 0.01);
  for (let i = 0; i < n; i++) {
    out[i] *= Math.sin((Math.PI * i) / n) ** 1.5;
  }
  return normalize(deClick(out), 0.6);
}

/** A number landing. Low sine drop with a body hit on top. */
function impact(): Buf {
  const out = buffer(0.55, SFX_RATE);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    const f = pitchRamp(i, out.length, 150, 42);
    phase += (2 * Math.PI * f) / SFX_RATE;
    out[i] = Math.sin(phase) * env(i, out.length, { decay: 0.55, curve: 5 });
  }
  const body = buffer(0.12, SFX_RATE);
  for (let i = 0; i < body.length; i++) {
    body[i] = rnd() * env(i, body.length, { decay: 0.3, curve: 8 });
  }
  mix(out, lowpass(body, 0.06), 0.7);
  return normalize(deClick(out), 0.95);
}

/** Dread under a statement. Long, slow, felt more than heard. */
function rumble(): Buf {
  const out = buffer(1.6, SFX_RATE);
  let p1 = 0;
  let p2 = 0;
  for (let i = 0; i < out.length; i++) {
    const f = pitchRamp(i, out.length, 58, 33);
    p1 += (2 * Math.PI * f) / SFX_RATE;
    p2 += (2 * Math.PI * f * 1.5) / SFX_RATE;
    const e = env(i, out.length, { attack: 0.12, decay: 0.9, curve: 3 });
    out[i] = (Math.sin(p1) + 0.3 * Math.sin(p2)) * e;
  }
  const air = buffer(1.6, SFX_RATE);
  for (let i = 0; i < air.length; i++) {
    air[i] = rnd() * env(i, air.length, { attack: 0.2, decay: 0.8, curve: 3 });
  }
  mix(out, lowpass(air, 0.02), 0.5);
  return normalize(deClick(out, 512), 0.85);
}

/** Money. Two struck bells, the second a fifth up and slightly late. */
function kaching(): Buf {
  const out = buffer(0.75, SFX_RATE);

  const bell = (freq: number, seconds: number): Buf => {
    const b = buffer(seconds, SFX_RATE);
    let carrier = 0;
    let mod = 0;
    for (let i = 0; i < b.length; i++) {
      const e = env(i, b.length, { decay: 0.45, curve: 5 });
      mod += (2 * Math.PI * freq * 2.76) / SFX_RATE; // inharmonic ratio: metal
      carrier += (2 * Math.PI * freq) / SFX_RATE + 0.6 * e * Math.sin(mod) * 0.02;
      b[i] = Math.sin(carrier) * e;
    }
    return b;
  };

  mix(out, bell(1046, 0.6), 0.7);
  mix(out, bell(1568, 0.55), 0.6, Math.round(0.075 * SFX_RATE));
  return normalize(deClick(out), 0.75);
}

/** Danger. Broken bursts, deliberately ugly. */
function glitch(): Buf {
  const out = buffer(0.45, SFX_RATE);
  let cursor = 0;
  while (cursor < out.length - 800) {
    const len = Math.round((0.01 + Math.abs(rnd()) * 0.05) * SFX_RATE);
    const step = 1 + Math.floor(Math.abs(rnd()) * 12); // sample-and-hold: crush
    let held = 0;
    for (let i = 0; i < len && cursor + i < out.length; i++) {
      if (i % step === 0) held = rnd();
      out[cursor + i] = held * env(i, len, { decay: 0.6, curve: 3 });
    }
    cursor += len + Math.round(Math.abs(rnd()) * 0.03 * SFX_RATE);
  }
  return normalize(deClick(highpass(out, 0.05)), 0.55);
}

/** The smallest cue there is — one item of many appearing or vanishing. */
function tick(): Buf {
  const out = buffer(0.045, SFX_RATE);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    phase += (2 * Math.PI * 2400) / SFX_RATE;
    out[i] = Math.sin(phase) * env(i, out.length, { decay: 0.25, curve: 9 });
  }
  const n = buffer(0.012, SFX_RATE);
  for (let i = 0; i < n.length; i++) n[i] = rnd() * (1 - i / n.length) ** 2;
  mix(out, highpass(n, 0.3), 0.4);
  return normalize(deClick(out, 16), 0.45);
}

/** The turn from crisis to solution: something lifting, then landing. */
function riser(): Buf {
  const out = buffer(2.0, SFX_RATE);
  const n = out.length;

  const noise = new Float32Array(n);
  for (let i = 0; i < n; i++) noise[i] = rnd();
  const opening = lowpass(noise, (i) => 0.008 + 0.35 * (i / n) ** 2);
  for (let i = 0; i < n; i++) opening[i] *= (i / n) ** 1.4;
  mix(out, opening, 0.8);

  let phase = 0;
  for (let i = 0; i < n; i++) {
    const f = pitchRamp(i, n, 110, 880);
    phase += (2 * Math.PI * f) / SFX_RATE;
    // A soft saw, quiet under the noise.
    out[i] += (((phase / Math.PI) % 2) - 1) * 0.18 * (i / n) ** 2;
  }
  return normalize(deClick(out, 1024), 0.7);
}

/** Between scenes: air moving, then the new frame arriving. */
function transition(): Buf {
  const out = buffer(0.6, SFX_RATE);
  const n = out.length;
  const noise = new Float32Array(n);
  for (let i = 0; i < n; i++) noise[i] = rnd();

  // Filter closing rather than opening — the sound falls into the cut.
  const swept = lowpass(noise, (i) => 0.45 * (1 - i / n) ** 1.5 + 0.01);
  for (let i = 0; i < n; i++) swept[i] *= Math.sin((Math.PI * i) / n) ** 0.8;
  mix(out, swept, 0.7);

  const thud = buffer(0.25, SFX_RATE);
  let phase = 0;
  for (let i = 0; i < thud.length; i++) {
    const f = pitchRamp(i, thud.length, 120, 50);
    phase += (2 * Math.PI * f) / SFX_RATE;
    thud[i] = Math.sin(phase) * env(i, thud.length, { decay: 0.4, curve: 6 });
  }
  mix(out, thud, 0.55, Math.round(0.3 * SFX_RATE));
  return normalize(deClick(out), 0.6);
}

// ---------------------------------------------------------------------------
// The beds. Eight seconds each, looped under the whole film.
// ---------------------------------------------------------------------------

const BED_SECONDS = 8;

/**
 * A bed is built only from components whose period divides the loop exactly,
 * so the seam falls on a zero crossing of everything at once. Frequencies are
 * chosen as whole numbers of cycles per eight seconds for that reason.
 */
function bed(opts: {
  root: number;
  interval: number;
  brightness: number;
  pulseGain: number;
  tickGain: number;
}): Buf {
  const extra = 0.4; // rendered long, then folded back for the seam
  const n = Math.round((BED_SECONDS + extra) * BED_RATE);
  const out = new Float32Array(n);

  // Drone: two slightly detuned saws plus the interval above them.
  const voices = [opts.root, opts.root + 0.125, opts.root * opts.interval];
  for (const [v, freq] of voices.entries()) {
    let phase = 0;
    for (let i = 0; i < n; i++) {
      phase += (2 * Math.PI * freq) / BED_RATE;
      const saw = ((phase / Math.PI) % 2) - 1;
      // Breathing filter, one full cycle across the loop.
      const swell = 0.5 + 0.5 * Math.sin((2 * Math.PI * i) / (BED_SECONDS * BED_RATE));
      out[i] += saw * (v === 2 ? 0.22 : 0.35) * (0.6 + 0.4 * swell);
    }
  }

  const shaped = lowpass(out, (i) => {
    const swell = 0.5 + 0.5 * Math.sin((2 * Math.PI * i) / (BED_SECONDS * BED_RATE));
    return opts.brightness * (0.5 + 0.5 * swell);
  });
  for (let i = 0; i < n; i++) out[i] = shaped[i];

  // The countdown: a sub pulse on every beat and a dry tick on the offbeat.
  const beat = Math.round(0.5 * BED_RATE);
  for (let start = 0; start < n; start += beat) {
    const len = Math.round(0.22 * BED_RATE);
    let phase = 0;
    for (let i = 0; i < len && start + i < n; i++) {
      const f = pitchRamp(i, len, 70, 45);
      phase += (2 * Math.PI * f) / BED_RATE;
      out[start + i] +=
        Math.sin(phase) * env(i, len, { decay: 0.35, curve: 6 }) * opts.pulseGain;
    }

    const tickAt = start + Math.round(beat / 2);
    const tLen = Math.round(0.03 * BED_RATE);
    for (let i = 0; i < tLen && tickAt + i < n; i++) {
      out[tickAt + i] +=
        rnd() * env(i, tLen, { decay: 0.2, curve: 10 }) * opts.tickGain;
    }
  }

  return normalize(loopSeam(out, extra, BED_RATE), 0.5);
}


// --- Quiz cues -------------------------------------------------------------
//
// The quiz format needs a different vocabulary from the infographics one. Its
// sounds are not there to underline a statement; they are there to tell you
// what just happened in a game — the clock is running, you were right, you
// were wrong, here comes the next one — and that has to read in under half a
// second without anybody explaining it.

/** The reveal when the answer is correct: two notes up, bright and settled. */
function ding(): Buf {
  const out = buffer(0.65, SFX_RATE);
  // A fifth apart and arriving a beat late, because a single tone reads as a
  // notification while two read as an answer.
  for (const [freq, at, gain] of [
    [880, 0, 1],
    [1318.5, 0.075, 0.85],
  ] as const) {
    const start = Math.round(at * SFX_RATE);
    let phase = 0;
    for (let i = 0; start + i < out.length; i++) {
      phase += (2 * Math.PI * freq) / SFX_RATE;
      out[start + i] +=
        (Math.sin(phase) + 0.25 * Math.sin(2 * phase)) *
        env(i, out.length - start, { decay: 0.45, curve: 4 }) *
        gain;
    }
  }
  return normalize(deClick(out), 0.72);
}

/** The reveal when it is wrong: a short, flat, downward buzz. */
function buzz(): Buf {
  const out = buffer(0.32, SFX_RATE);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    const f = pitchRamp(i, out.length, 220, 150);
    phase += (2 * Math.PI * f) / SFX_RATE;
    // Square-ish, because a clean sine sounds pleasant and this must not.
    const square = Math.sign(Math.sin(phase)) * 0.5 + Math.sin(phase) * 0.5;
    out[i] = square * env(i, out.length, { decay: 0.55, curve: 3.5 });
  }
  return normalize(lowpass(deClick(out), 0.25), 0.55);
}

/** The clock, one tick. Drier and higher than the infographics tick. */
function clockTick(): Buf {
  const out = buffer(0.05, SFX_RATE);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    phase += (2 * Math.PI * 3200) / SFX_RATE;
    out[i] = Math.sin(phase) * env(i, out.length, { decay: 0.16, curve: 12 });
  }
  const n = buffer(0.008, SFX_RATE);
  for (let i = 0; i < n.length; i++) n[i] = rnd() * (1 - i / n.length) ** 2;
  mix(out, highpass(n, 0.45), 0.5);
  return normalize(deClick(out, 12), 0.38);
}

/** The wipe between questions: air moving, no pitch. */
function whoosh(): Buf {
  const out = buffer(0.4, SFX_RATE);
  for (let i = 0; i < out.length; i++) {
    const t = i / out.length;
    // Loudest in the middle, so it reads as something passing rather than
    // starting or stopping.
    out[i] = rnd() * Math.sin(Math.PI * t) ** 2;
  }
  const swept = lowpass(out, (i) => 0.08 + 0.5 * Math.sin(Math.PI * (i / out.length)));
  return normalize(deClick(highpass(swept, 0.04)), 0.5);
}

/** The last seconds of the clock: the tick, but urgent. */
function tickUrgent(): Buf {
  const out = buffer(0.05, SFX_RATE);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    phase += (2 * Math.PI * 4200) / SFX_RATE;
    out[i] = Math.sin(phase) * env(i, out.length, { decay: 0.14, curve: 13 });
  }
  return normalize(deClick(out, 12), 0.5);
}

/**
 * The gameshow bed.
 *
 * Built on a different principle from the infographics beds. Those hold one
 * unresolved chord because they sit under a narrator making a point; this one
 * has a walking bass and an off-beat stab, because it sits under a clock and
 * its job is to make five seconds of waiting feel like five seconds of playing.
 */
function quizBed(opts: { root: number; bpm: number; bright: number }): Buf {
  const beat = (60 / opts.bpm) * BED_RATE;
  const bars = 4;
  const beats = bars * 4;
  const extra = 0.5;
  const out = buffer((beats * beat) / BED_RATE + extra, BED_RATE);
  const n = out.length;

  // A major-pentatonic walk: cheerful without being a melody anyone has to
  // listen to.
  const steps = [0, 4, 7, 4, 0, 7, 9, 7];

  for (let b = 0; b < beats; b++) {
    const start = Math.round(b * beat);
    const semitone = steps[b % steps.length];
    const freq = opts.root * Math.pow(2, semitone / 12);

    // Bass: short, plucked, on every beat.
    const bassLen = Math.round(beat * 0.9);
    let phase = 0;
    for (let i = 0; i < bassLen && start + i < n; i++) {
      phase += (2 * Math.PI * freq) / BED_RATE;
      out[start + i] +=
        (Math.sin(phase) + 0.3 * Math.sin(2 * phase)) *
        env(i, bassLen, { decay: 0.28, curve: 5 }) *
        0.55;
    }

    // Stab on the off-beat, two octaves up. This is the part that makes it
    // sound like a game rather than a loop.
    const offAt = start + Math.round(beat * 0.5);
    const stabLen = Math.round(beat * 0.4);
    let sp = 0;
    for (let i = 0; i < stabLen && offAt + i < n; i++) {
      sp += (2 * Math.PI * freq * 4) / BED_RATE;
      out[offAt + i] +=
        Math.sin(sp) * env(i, stabLen, { decay: 0.22, curve: 7 }) * opts.bright;
    }

    // A hat on every half beat: the pulse you feel rather than hear.
    for (const at of [start, offAt]) {
      const hLen = Math.round(0.02 * BED_RATE);
      for (let i = 0; i < hLen && at + i < n; i++) {
        out[at + i] += rnd() * env(i, hLen, { decay: 0.18, curve: 11 }) * 0.12;
      }
    }
  }

  // A sustained chord under all of it.
  //
  // Without this the bed is nothing but plucks and gaps: it peaked fine and
  // measured an RMS of 0.05, which is why it disappeared under everything the
  // moment it was mixed in. Continuous energy is what makes music sit *under*
  // a video rather than poke through it, and it is the difference between a
  // loop you notice and a loop you feel.
  for (const mult of [1, 1.5, 2]) {
    let phase = 0;
    for (let i = 0; i < n; i++) {
      phase += (2 * Math.PI * opts.root * mult) / BED_RATE;
      // Slow tremolo so the pad breathes instead of sitting there as a drone.
      const breath = 0.85 + 0.15 * Math.sin((2 * Math.PI * i) / (BED_RATE * 1.7));
      out[i] += Math.sin(phase) * 0.13 * breath * (mult === 1 ? 1 : 0.6);
    }
  }

  return normalize(loopSeam(out, extra, BED_RATE), 0.8);
}

// ---------------------------------------------------------------------------

function main(): void {
  mkdirSync(OUT, { recursive: true });
  console.log("[audio] Cues:");
  writeWav("pop.wav", pop(), SFX_RATE);
  writeWav("swoosh.wav", swoosh(), SFX_RATE);
  writeWav("impact.wav", impact(), SFX_RATE);
  writeWav("rumble.wav", rumble(), SFX_RATE);
  writeWav("kaching.wav", kaching(), SFX_RATE);
  writeWav("glitch.wav", glitch(), SFX_RATE);
  writeWav("tick.wav", tick(), SFX_RATE);
  writeWav("riser.wav", riser(), SFX_RATE);
  writeWav("transition.wav", transition(), SFX_RATE);

  console.log("[audio] Quiz-Cues:");
  writeWav("q-ding.wav", ding(), SFX_RATE);
  writeWav("q-buzz.wav", buzz(), SFX_RATE);
  writeWav("q-tick.wav", clockTick(), SFX_RATE);
  writeWav("q-tick-urgent.wav", tickUrgent(), SFX_RATE);
  writeWav("q-whoosh.wav", whoosh(), SFX_RATE);

  console.log("[audio] Beds:");
  writeWav(
    "bed-crisis.wav",
    bed({
      root: 55,
      interval: 1.5, // a bare fifth: unresolved, uneasy
      brightness: 0.05,
      pulseGain: 0.5,
      tickGain: 0.16,
    }),
    BED_RATE,
  );
  writeWav(
    "bed-solution.wav",
    bed({
      root: 55,
      interval: 1.6875, // major sixth: the same room, lit differently
      brightness: 0.1,
      pulseGain: 0.32,
      tickGain: 0.09,
    }),
    BED_RATE,
  );

  // One bed per difficulty, faster and brighter as it climbs — the same
  // progression the colours make, in the one channel nobody can look away from.
  writeWav("q-bed-easy.wav", quizBed({ root: 110, bpm: 104, bright: 0.2 }), BED_RATE);
  writeWav("q-bed-medium.wav", quizBed({ root: 110, bpm: 116, bright: 0.26 }), BED_RATE);
  writeWav("q-bed-hard.wav", quizBed({ root: 123.5, bpm: 128, bright: 0.32 }), BED_RATE);
  writeWav("q-bed-impossible.wav", quizBed({ root: 138.6, bpm: 140, bright: 0.38 }), BED_RATE);
}

main();
